import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Difficulty, PuzzleType, usePuzzle } from "@/state/puzzle";
import { generate8Puzzle } from "@/ai/eightPuzzle";
import { generateSudoku } from "@/ai/sudoku";
import { generateMaze } from "@/ai/maze";
import { EightPuzzleBoard } from "@/components/boards/EightPuzzleBoard";
import { SudokuBoard } from "@/components/boards/SudokuBoard";
import { MazeBoard } from "@/components/boards/MazeBoard";
import { RefreshCw, ArrowRight } from "lucide-react";

const DIFFS: Difficulty[] = ["easy", "medium", "hard"];

const Generate = () => {
  const { state, setState } = usePuzzle();
  const [tick, setTick] = useState(0);
  const navigate = useNavigate();

  const generate = () => {
    if (state.type === "8puzzle") setState({ eight: generate8Puzzle(state.difficulty) });
    if (state.type === "sudoku") setState({ sudoku: generateSudoku(state.difficulty) });
    if (state.type === "maze") setState({ maze: generateMaze(state.difficulty) });
    setTick((x) => x + 1);
  };

  useEffect(() => { generate(); /* eslint-disable-next-line */ }, [state.type, state.difficulty]);

  return (
    <main className="container py-10">
      <div className="mb-8">
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Step 01</p>
        <h1 className="text-3xl font-bold md:text-4xl">Generate a puzzle</h1>
        <p className="mt-2 text-muted-foreground">Puzzles are generated procedurally — guaranteed valid, solvable, and non-trivial.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
        <aside className="panel space-y-6 p-5">
          <div>
            <label className="mb-2 block font-mono text-xs uppercase tracking-wider text-muted-foreground">Puzzle type</label>
            <Tabs value={state.type} onValueChange={(v) => setState({ type: v as PuzzleType })}>
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="8puzzle">8-Puzzle</TabsTrigger>
                <TabsTrigger value="sudoku">Sudoku</TabsTrigger>
                <TabsTrigger value="maze">Maze</TabsTrigger>
              </TabsList>
            </Tabs>
          </div>

          <div>
            <label className="mb-2 block font-mono text-xs uppercase tracking-wider text-muted-foreground">Difficulty</label>
            <div className="grid grid-cols-3 gap-2">
              {DIFFS.map((d) => (
                <button key={d} onClick={() => setState({ difficulty: d })}
                  className={`rounded-md border px-3 py-2 text-sm capitalize transition ${state.difficulty === d ? "border-primary bg-primary/10 text-primary" : "border-border bg-muted/30 text-muted-foreground hover:text-foreground"}`}>
                  {d}
                </button>
              ))}
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <Button onClick={generate} variant="outline"><RefreshCw className="mr-2 h-4 w-4" /> Regenerate</Button>
            <Button asChild className="bg-gradient-primary text-primary-foreground hover:opacity-90">
              <Link to="/solve">Continue to solver <ArrowRight className="ml-2 h-4 w-4" /></Link>
            </Button>
          </div>

          <div className="rounded-lg border border-border bg-muted/30 p-3 text-xs text-muted-foreground">
            {state.type === "8puzzle" && "Generated by walking backwards from the goal — guarantees solvability without parity tricks."}
            {state.type === "sudoku" && "A full grid is solved with randomized backtracking; cells are then removed based on difficulty."}
            {state.type === "maze" && "Recursive-backtracker carves a perfect maze on an odd-sized grid; every cell is reachable."}
          </div>
        </aside>

        <section className="panel grid place-items-center p-8 min-h-[420px]">
          <div key={tick} className="animate-fade-in">
            {state.type === "8puzzle" && state.eight && (
              <div className="w-[300px]"><EightPuzzleBoard board={state.eight} /></div>
            )}
            {state.type === "sudoku" && state.sudoku && <SudokuBoard puzzle={state.sudoku.puzzle} />}
            {state.type === "maze" && state.maze && <MazeBoard maze={state.maze} />}
          </div>
        </section>
      </div>
    </main>
  );
};

export default Generate;
